using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class ChatInfo : MonoBehaviour
{
    public ArrayList usernames = new ArrayList()
    {
        "StreamerMaster",
        "GamingGuru",
        "ProGamer123",
        "LuckyLurker007",
        "ViewerChampion",
        "SpeedyStreamer",
        "ChatModExpert",
        "StreamNinja",
        "GamerGuy55",
        "GamerGeek",
        "LurkAndLearn",
        "StreamerProMax",
        "NoobCrusher",
        "ProViewer1234",
        "GamingLegend",
        "StreamerDude",
        "TwitchQueen123",
        "CoolStreamer42",
        "AwesomeStreamer007",
        "LuckyViewer777",
        "CasualGamer",
        "ProGamer99",
        "StreamerExtraordinaire",
        "EpicGamer23",
        "ProViewer55",
        "TwitchAddict",
        "GamingGoddess",
        "NewbieViewer",
        "ViewersChoice",
        "StreamerNation",
        "GamerProdigy",
        "TwitchWizard",
        "ViewerWarrior",
        "GameOnStreamer",
        "RetroGamer",
        "StreamerGigabyte",
        "ProNoob123",
        "UltimateStreamer",
        "TwitchLurkerX",
        "MasterOfGames",
        "StreamSorcerer",
        "GamerHero",
        "StreamProdigy",
        "LurkingLegend",
        "ChatModChampion",
        "LoyalViewer101",
        "GamingMaestro",
        "TwitchSavant",
        "StreamerSupreme",
        "GamerCrusader",
        "ViewerVoyager",
        "GamingArchitect",
        "StreamSensei",
        "ProLurkerX",
        "UltimateViewing",
        "TwitchTrailblazer",
        "StreamingLegend",
        "GamerKingpin",
        "ViewerSorcerer",
        "StreamerChampion",
        "TwitchGenius",
        "GamingVirtuoso",
        "NoobCrusherX",
        "StreamPhenomenon",
        "ChatModMaster",
        "StreamSensation",
        "TwitchSorceress",
        "ProViewerX",
        "ViewerVirtuoso",
        "StreamerMaverick",
        "GamingGenius",
        "TwitchSultan",
        "GamingCrusader",
        "LuckyLurker123",
        "StreamWarlord",
        "GamerVirtuoso",
        "TwitchSorcery",
        "UltimateViewers",
        "ProStreamerX",
        "ViewerElite",
        "StreamerProMax",
        "GamingProdigy",
        "GamingXpert",
        "LoyalLurker",
        "StreamSenseiX",
        "TwitchSavvyX",
        "StreamerSupremacy",
        "GamerXperience",
        "ViewerValhalla",
        "StreamerEnigma",
        "GamingProX",
        "StreamSorceressX",
        "ChatModGuru",
        "TwitchVoyager",
        "StreamerSeraph",
        "UltimateStreamers",
        "ViewerVortex",
        "GamingGalacticX",
        "StreamWarlock",
        "GamerLegends",
        "TwitchEnigmaX",
        "GamingVoyager",
        "LuckyLurkerX",
        "StreamChampion",
        "StreamerSanctuary",
        "GamerProdigyX",
        "TwitchGeniusX",
        "UltimateLurker",
        "ViewerMystic",
        "StreamerSiren",
        "GameOnMaster",
        "StreamerXperts",
        "TwitchWiz",
        "LoyalLurkerX",
        "StreamMysticX",
        "GamerSupreme",
        "ProStreamers",
        "TwitchSorceryX",
        "GamingWiz",
        "ViewerMaster",
        "StreamSorcererX",
        "ChatModExpertX",
        "TwitchSavvyXX",
        "LuckyLurkerXX",
        "StreamerKingpin",
        "ProNoobX",
        "GamerChampion",
        "ViewerChampionX",
        "TwitchCrusader",
        "GamingPhenom",
        "StreamMaverick",
        "UltimateGamerX",
        "ProStreamWizard",
        "TwitchProdigyX",
        "GamerGoddess",
        "LoyalStreamer",
        "StreamMastermind",
        "StreamerProX",
        "TwitchVoyagerX",
        "GamingWarlord",
        "ChatModHero",
        "GamerXpertX",
        "TwitchVirtuoso",
        "StreamingMaverick",
        "LuckyStreamers",
        "ProGamerXperience",
        "StreamerArchitect",
        "GamerWizard",
        "ViewerSorcererX",
        "UltimateViewersX",
        "StreamWarriorX",
        "TwitchGeniusXX",
        "GamingVirtuosoX",
        "LoyalCrusader",
        "GamerProdigyXX",
        "StreamerSavant",
        "TwitchSorceressX",
        "ProViewerGuru",
        "StreamerEnigmaX",
        "GamingProXpert",
        "StreamSorceressX",
        "UltimateGamerXX",
        "ViewerVirtuosoX",
        "TwitchSultanX",
        "GamingCrusaderX",
        "LuckyLurker123X",
        "StreamerWarlordX",
        "GamerVirtuosoX",
        "TwitchSorceryX",
        "UltimateViewersXX",
        "ProStreamerXpert",
        "ViewerEliteX",
        "StreamerProXpert",
        "GamingProdigyXpert",
        "GamingXpertX",
        "LoyalLurkerXpert",
        "StreamSenseiXpert",
        "TwitchSavvyXpert",
        "StreamerSupremacyX",
        "GamerXperienceX",
        "ViewerValhallaXpert",
        "StreamerEnigmaXpert",
        "GamingProXpertX",
        "StreamSorceressXpert",
        "ChatModGuruX",
        "TwitchVoyagerXpert",
        "StreamerSeraphX",
        "UltimateStreamersX",
        "ViewerVortexX",
        "GamingGalacticXpert",
        "StreamWarlockX",
        "GamerLegendsX",
        "TwitchEnigmaXpertX",
        "GamingVoyagerXpert",
        "LuckyLurkerXpertX",
        "StreamChampionX",
        "StreamerSanctuaryX",
        "GamerProdigyXpertX",
        "TwitchGeniusXpertX",
        "UltimateLurkerXpert",
        "ViewerMysticXpert",
        "StreamerSirenX",
        "GameOnMasterX"
    };

    public ArrayList messages = new ArrayList() { "Hi", "Hello", "Good Evening", "Ahhh that was a scary vid", "W jumpscare", "Awesome content", "Love your stuff dude", "What's up man", "L", "W", "Nice", "Pog", "???", "Bruh", "No way", "Unbelievable", ":)", ":o", "W game", "U suck", "Love the streams"};

    public ArrayList stalkerUsernames = new ArrayList() { "DarkQuan88", "EvilQuan45", "NightStalker32", "YourBestFriend", "YourBiggestFan", "CreepQuan71", "ILoveYouStreamer", "#1Stalker", "QuanMan89", "HunterQuan63", "EvilYoungster", "SomeEvilGuy", "DangerousPerson68", "SinisterSigma03", "WickedDummy47", "FoulChap", "DarkFigure00", "SketchyGeezer", "VileBloke97"};

    public ArrayList stalkerMessages = new ArrayList () {"You suck at this game.",
        "I'm gonna find you.",
        "I wish I could meet you and hang out wiht you",
        "Do you ever feel unsafe in your own home?",
        "Do you ever feel like someone is watching you?",
        "What would you do if one of your viewers came to your house?",
        "Where do you live?",
        "I know where you live.", 
        "Your house is bigger than I thought.",
        "I can see you.",
        "I made a shrine for you.", 
        "I love everything about you.", };
}


